apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
data:
  username: "YWRtaW4K"  #pls check once   echo admin | base64 YWRtaW4K

  password: "YWRtaW4xMjMK"  #pls check once   echo admin123 | base64  YWRtaW4xMjMK

  
