kind: Pod     #POD creating
apiVersion: v1
metadata:
  name: nginx
  labels:                 #service to pod communication
    name: frontend
    project: expense
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx